<script setup lang="ts">
import { ref } from "vue";
import CodeBlock from "../../components/CodeBlock.vue";
import DocsNavigation from "../../components/DocsNavigation.vue";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import Separator from "../../components/ui/Separator";

const schemaRaw = `{
  "$schema": "https://vueonui.com/schema.json",
  "framework": "vue-vite",
  "paths": {
    "components": "path to your components",
    "css": "path to your css"
  },
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "path to your css",
    "baseColor": "zinc"
  },
  "aliases": {
    "components": "@/components",
    "ui": "@/ui",
    "lib": "@/lib"
  },
  "iconLibrary": "lucide"
}`;
const schemaExample = ref(schemaRaw);
</script>

<template>
  <section class="space-y-6">
    <DocsNavigation
      :prev="{ title: 'blocks', path: '/docs/blocks' }"
      :next="{ title: null, path: null }"
    />
    <div>

        <h1 id="schema" class="text-3xl font-bold">Vueon-UI Project Schema</h1>
        <p class="text-muted-foreground mb-4">
            Define metadata for your project to help CLI and Vueon-UI components work seamlessly.
        </p>
    </div>

    <!-- Schema JSON Example -->
    <section class="rounded-b-md mb-4 ">
      <CodeBlock
        :hideheading="true"
        :code="schemaExample"
      />
    </section>

    <!-- Field explanations -->
    <div>
      <h4 id="schemafields" class="mb-3">Schema fields</h4>
      <Separator />

      <p class="text-md mt-4">"theme"</p>
      <p class="text-sm opacity-70">Color system and design tokens (like Tailwind Oklch).</p>

      <p class="text-md mt-2">"library"</p>
      <p class="text-sm opacity-70">Shows which libraries are used in your components.</p>

      <p class="text-md mt-2">"framework"</p>
      <p class="text-sm opacity-70">Which JS framework your project uses (Vue, React, etc.).</p>

      <p class="text-md mt-2">"components"</p>
      <p class="text-sm opacity-70">Path of UI components generated by the project.</p>

      <p class="text-md mt-2">"css"</p>
      <p class="text-sm opacity-70">Path where CSS files are updated/managed.</p>
    </div>

  </section>
</template>
